ALTER TABLE "Product" ADD COLUMN "brand" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "model" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "modelSourceUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "specsConfirmed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN "itemReviewConfirmed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN "cleanImageLicense" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "researchNotes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ShippingSetting" ADD COLUMN "ratesConfirmed" BOOLEAN NOT NULL DEFAULT false;
